events { }

http {
    include /etc/nginx/mime.types;
    
    server {
        listen              443 ssl;
        server_name         dakshin.xyz;
        ssl_certificate     /etc/nginx/dakshin.xyz.crt;
        ssl_certificate_key /etc/nginx/dakshin.xyz.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;


        location / {
            root /usr/share/nginx/html/;
        }
    }

    server {
        listen 80;

        server_name dakshin.xyz;

        return 301 https://dakshin.xyz$request_uri;
    }
}