- name: Deploy webserver
  hosts: all
  tasks:
    - name: Log into registry
      community.docker.docker_login:
        registry: ghcr.io
        username: "{{ REGISTRY_USERNAME }}"
        password: "{{ REGISTRY_PWD }}"
    - name: Run container
      community.docker.docker_container:
        image: "{{ IMAGE_URL }}"
        name: webpage
        pull: true
        restart_policy: always
        mounts:
          - source: /etc/letsencrypt/live/dakshin.xyz/fullchain.pem
            target: /etc/nginx/dakshin.xyz.crt
            type: bind
            read_only: true
          - source: /etc/letsencrypt/live/dakshin.xyz/privkey.pem
            target: /etc/nginx/dakshin.xyz.key
            type: bind
            read_only: true
        published_ports:
          - 80:80
          - 443:443
