name: build-webpage
run-name: build-webpage
on: [push]
jobs:
  build-webpage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: test-and-build
        run: |
          cd webpage
          yarn install --frozen-lockfile
          yarn test
          yarn build
